# Generated by Django 5.1.1 on 2026-02-03 09:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kkt_rfc_challenge', '0001_initial'),
        ('kkt_rfc_login', '0001_initial'),
        ('kkt_rfc_tour_guide', '0025_feedbackmodel_page_url_feedbackmodel_task_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionCodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('code', models.CharField(help_text='促销码文本（如 HOLIDAY20）', max_length=128, unique=True)),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Percent'), ('FIXED', 'Fixed')], help_text='折扣类型', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='PERCENT 时表示百分比（如 20=20%）；FIXED 时表示固定减免金额', max_digits=10)),
                ('valid_from', models.DateTimeField(blank=True, help_text='有效期开始', null=True)),
                ('valid_to', models.DateTimeField(blank=True, help_text='有效期结束', null=True)),
                ('usage_limit_total', models.IntegerField(blank=True, help_text='全局使用次数上限', null=True)),
                ('usage_limit_per_identity', models.IntegerField(blank=True, help_text='每个游客主体（visitor）使用次数上限', null=True)),
                ('meta', models.JSONField(blank=True, default=dict, help_text='扩展信息（适用商品范围、备注等）')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SellItemBundleItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.IntegerField(default=1)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'kkt_rfc_order_sell_item_bundle_item',
            },
        ),
        migrations.CreateModel(
            name='SellItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, help_text='售卖项编码（用于配置/对接/运营导入）', max_length=128, unique=True)),
                ('is_bundle', models.BooleanField(db_index=True, default=False, help_text='是否为"组合套餐售卖项"（false：普通单品；true：套餐，其组成由 sell_item_bundle_item 定义）')),
                ('purchasable_identity', models.CharField(choices=[('ACTIVATION_CODE_ONLY', 'Activation Code Only'), ('NFC_ONLY', 'NFC Only'), ('BOTH', 'Both')], default='BOTH', help_text='可购买人群', max_length=20)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'kkt_rfc_order_sell_item',
            },
        ),
        migrations.CreateModel(
            name='SellItemTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('MEMORY', 'Memory'), ('TICKET', 'Ticket'), ('FOOD', 'Food'), ('ACTIVATION_CODE', 'Activation Code'), ('CHALLENGE_PRIZE', 'Challenge Prize')], db_index=True, help_text='类型编码', max_length=64, unique=True)),
                ('activation_mode', models.CharField(choices=[('REDEEM_REQUIRED', 'Redeem Required'), ('IMMEDIATE', 'Immediate'), ('NONE', 'None')], help_text='激活方式', max_length=20)),
                ('meta', models.JSONField(blank=True, default=dict, help_text='扩展配置')),
            ],
            options={
                'db_table': 'kkt_rfc_order_sell_item_type',
            },
        ),
        migrations.CreateModel(
            name='VoucherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, help_text='券码（二维码内容，一次性兑换凭证）', max_length=128, unique=True)),
                ('voucher_type', models.CharField(choices=[('REDEEM', 'Redeem'), ('CHALLENGE_PRIZE', 'Challenge Prize')], db_index=True, max_length=30)),
                ('issued_seq', models.IntegerField(default=1)),
                ('meta', models.JSONField(blank=True, default=dict, help_text='扩展信息')),
            ],
            options={
                'db_table': 'kkt_rfc_order_voucher',
            },
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', help_text='订单状态', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='实付金额', max_digits=10)),
                ('currency', models.CharField(default='CNY', help_text='币种', max_length=8)),
                ('sales_channel', models.CharField(blank=True, choices=[('ONLINE_STORE', 'Online Store'), ('OFFLINE_POI', 'Offline POI'), ('OTHER', 'Other')], help_text='销售渠道', max_length=20, null=True)),
                ('payment_provider', models.CharField(blank=True, choices=[('WECHAT', 'WeChat'), ('ALIPAY', 'Alipay'), ('MOCK', 'Mock')], help_text='支付渠道', max_length=20, null=True)),
                ('payment_transaction_id', models.CharField(blank=True, db_index=True, help_text='第三方支付流水号（用于退款/对账）', max_length=128, null=True)),
                ('paid_at', models.DateTimeField(blank=True, db_index=True, help_text='支付完成时间', null=True)),
                ('buyer_email', models.EmailField(blank=True, help_text='收券/通知邮箱（当 visitor_id 为空（仅激活码订单）时必填；其余场景可选（用于发券通知/客服沟通））', max_length=255, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('sales_poi', models.ForeignKey(blank=True, help_text='销售发生的POI', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kkt_rfc_tour_guide.poimodel')),
                ('visitor', models.ForeignKey(blank=True, help_text='关联购买者，仅当 order.sell_item.sell_item_type.code = ACTIVATION_CODE 时允许为空；其余订单必须有关联的 visitor', null=True, on_delete=django.db.models.deletion.CASCADE, to='kkt_rfc_login.visitormodel')),
            ],
            options={
                'db_table': 'kkt_rfc_order_order',
            },
        ),
        migrations.CreateModel(
            name='OrderItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.IntegerField(default=1)),
                ('unit_amount', models.DecimalField(blank=True, decimal_places=2, help_text='行单价', max_digits=10, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='行小计,等于 unit_amount*qty', max_digits=10, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('order', models.ForeignKey(help_text='关联订单', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kkt_rfc_order.ordermodel')),
            ],
            options={
                'db_table': 'kkt_rfc_order_order_item',
            },
        ),
        migrations.CreateModel(
            name='EntitlementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('USED_UP', 'Used Up'), ('EXPIRED', 'Expired')], default='PENDING', help_text='权益状态', max_length=20)),
                ('remaining_qty', models.IntegerField(blank=True, null=True)),
                ('start_at', models.DateTimeField(blank=True, help_text='生效开始时间（用于有效期窗口）', null=True)),
                ('end_at', models.DateTimeField(blank=True, help_text='生效结束时间（过期时间）', null=True)),
                ('meta', models.JSONField(blank=True, default=dict, help_text='扩展信息（规则快照、核销限制、配额明细等）')),
                ('challenge', models.ForeignKey(blank=True, help_text='来源挑战', null=True, on_delete=django.db.models.deletion.CASCADE, to='kkt_rfc_challenge.challengemodel')),
                ('visitor', models.ForeignKey(help_text='权益归属的游客主体', on_delete=django.db.models.deletion.CASCADE, to='kkt_rfc_login.visitormodel')),
                ('order_item', models.ForeignKey(blank=True, help_text='用于套餐/多行订单的精确追溯与对账；奖励/补发可为空', null=True, on_delete=django.db.models.deletion.CASCADE, to='kkt_rfc_order.orderitemmodel')),
                ('order', models.ForeignKey(blank=True, help_text='来源订单（奖励可为空）', null=True, on_delete=django.db.models.deletion.CASCADE, to='kkt_rfc_order.ordermodel')),
            ],
            options={
                'db_table': 'kkt_rfc_order_entitlement',
            },
        ),
        migrations.CreateModel(
            name='PromotionCodeUsageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='本次抵扣金额（便于对账与审计）', max_digits=10, null=True)),
                ('used_at', models.DateTimeField(default=django.utils.timezone.now, help_text='使用时间')),
                ('meta', models.JSONField(blank=True, default=dict, help_text='扩展信息')),
                ('order', models.ForeignKey(help_text='关联订单', on_delete=django.db.models.deletion.CASCADE, related_name='promotion_code_usages', to='kkt_rfc_order.ordermodel')),
                ('promotion_code', models.ForeignKey(help_text='关联促销码', on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='kkt_rfc_order.promotioncodemodel')),
                ('visitor', models.ForeignKey(blank=True, help_text='关联使用者 visitor（为空场景：未登录但下单的文创购买）', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kkt_rfc_login.visitormodel')),
            ],
            options={
                'db_table': 'kkt_rfc_order_promotion_code_usage',
            },
        ),
        migrations.CreateModel(
            name='RedemptionLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('VOUCHER_REDEEM', 'Voucher Redeem'), ('CHALLENGE_CHECKIN', 'Challenge Checkin')], help_text='事件类型', max_length=50)),
                ('source', models.CharField(choices=[('TERMINAL', 'Terminal'), ('MINIPROGRAM', 'MiniProgram'), ('ADMIN', 'Admin')], help_text='来源端', max_length=30)),
                ('request_id', models.CharField(help_text='幂等键（终端/客户端生成；用于防重复扣减/重复兑换）', max_length=128, unique=True)),
                ('result', models.CharField(choices=[('SUCCESS', 'Success'), ('FAIL', 'Fail')], help_text='结果', max_length=20)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('entitlement', models.ForeignKey(blank=True, help_text='关联权益单据', null=True, on_delete=django.db.models.deletion.CASCADE, to='kkt_rfc_order.entitlementmodel')),
                ('poi', models.ForeignKey(blank=True, help_text='核销点', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kkt_rfc_tour_guide.poimodel')),
            ],
            options={
                'db_table': 'kkt_rfc_order_redemption_log',
            },
        ),
    ]
