# Generated by Django 5.1.1 on 2026-02-03 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kkt_i18n_translations', '0003_remove_i18nlabelmodel_ja_remove_i18nlinemodel_ja'),
        ('kkt_rfc_backend_route_plan', '0005_alter_availableroutemodel_poi'),
        ('kkt_rfc_login', '0002_initial'),
        ('kkt_rfc_order', '0001_initial'),
        ('kkt_rfc_pos_config', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='redemptionlogmodel',
            name='pos',
            field=models.ForeignKey(blank=True, help_text='执行核销的 POS 设备', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kkt_rfc_pos_config.pointofsaleterminalmodel'),
        ),
        migrations.AddField(
            model_name='redemptionlogmodel',
            name='user',
            field=models.ForeignKey(blank=True, help_text='终端登录的商户账号（执行者）', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='redemptionlogmodel',
            name='visitor',
            field=models.ForeignKey(blank=True, help_text='关联游客主体（可空场景：未登录的券兑换）', null=True, on_delete=django.db.models.deletion.CASCADE, to='kkt_rfc_login.visitormodel'),
        ),
        migrations.AddField(
            model_name='sellitemmodel',
            name='description',
            field=models.ForeignKey(blank=True, help_text='售卖项详情描述（长文案，多语言，可选）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sell_item_description_i18n', to='kkt_i18n_translations.i18nblockmodel'),
        ),
        migrations.AddField(
            model_name='sellitemmodel',
            name='name',
            field=models.ForeignKey(blank=True, help_text='售卖项名称（短文案，多语言）', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kkt_i18n_translations.i18nlinemodel'),
        ),
        migrations.AddField(
            model_name='sellitemmodel',
            name='route',
            field=models.ForeignKey(blank=True, help_text='可以关联一条游览线路', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kkt_rfc_backend_route_plan.routemodel'),
        ),
        migrations.AddField(
            model_name='sellitembundleitemmodel',
            name='bundle_sell_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='kkt_rfc_order.sellitemmodel'),
        ),
        migrations.AddField(
            model_name='sellitembundleitemmodel',
            name='component_sell_item',
            field=models.ForeignKey(blank=True, help_text='子售卖项（要求 sell_item.is_bundle=false）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='component_in_bundles', to='kkt_rfc_order.sellitemmodel'),
        ),
        migrations.AddField(
            model_name='redemptionlogmodel',
            name='sell_item',
            field=models.ForeignKey(blank=True, help_text='关联售卖项（权益核销/购买相关事件）', null=True, on_delete=django.db.models.deletion.CASCADE, to='kkt_rfc_order.sellitemmodel'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='sell_item',
            field=models.ForeignKey(help_text='关联购买的售卖项', on_delete=django.db.models.deletion.CASCADE, to='kkt_rfc_order.sellitemmodel'),
        ),
        migrations.AddField(
            model_name='orderitemmodel',
            name='sell_item',
            field=models.ForeignKey(blank=True, help_text='该行对应的"子售卖项"', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kkt_rfc_order.sellitemmodel'),
        ),
        migrations.AddField(
            model_name='entitlementmodel',
            name='sell_item',
            field=models.ForeignKey(blank=True, help_text='对应售卖项', null=True, on_delete=django.db.models.deletion.CASCADE, to='kkt_rfc_order.sellitemmodel'),
        ),
        migrations.AddField(
            model_name='sellitemtypemodel',
            name='description',
            field=models.ForeignKey(blank=True, help_text='类型说明（长文案，多语言，可选）', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kkt_i18n_translations.i18nblockmodel'),
        ),
        migrations.AddField(
            model_name='sellitemtypemodel',
            name='name',
            field=models.ForeignKey(blank=True, help_text='类型名称（短文案，多语言）', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kkt_i18n_translations.i18nlinemodel'),
        ),
        migrations.AddField(
            model_name='sellitemmodel',
            name='sell_item_type',
            field=models.ForeignKey(blank=True, help_text='售卖项类型', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kkt_rfc_order.sellitemtypemodel'),
        ),
        migrations.AddField(
            model_name='vouchermodel',
            name='entitlement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher', to='kkt_rfc_order.entitlementmodel'),
        ),
        migrations.AddField(
            model_name='vouchermodel',
            name='order',
            field=models.ForeignKey(blank=True, help_text='来源订单（文创购买券：关联订单；挑战奖品券：可为空）', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kkt_rfc_order.ordermodel'),
        ),
        migrations.AddField(
            model_name='vouchermodel',
            name='order_item',
            field=models.ForeignKey(blank=True, help_text='来源订单行,voucher_type=REDEEM 建议必填,CHALLENGE_PRIZE 可为空', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kkt_rfc_order.orderitemmodel'),
        ),
        migrations.AddField(
            model_name='vouchermodel',
            name='sell_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kkt_rfc_order.sellitemmodel'),
        ),
        migrations.AddField(
            model_name='redemptionlogmodel',
            name='voucher',
            field=models.ForeignKey(blank=True, help_text='关联券（兑换事件）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemption_events', to='kkt_rfc_order.vouchermodel'),
        ),
        migrations.AddIndex(
            model_name='promotioncodeusagemodel',
            index=models.Index(fields=['promotion_code'], name='kkt_rfc_ord_promoti_6fc349_idx'),
        ),
        migrations.AddIndex(
            model_name='promotioncodeusagemodel',
            index=models.Index(fields=['order'], name='kkt_rfc_ord_order_i_e2c4f5_idx'),
        ),
        migrations.AddIndex(
            model_name='promotioncodeusagemodel',
            index=models.Index(fields=['visitor'], name='kkt_rfc_ord_visitor_41f857_idx'),
        ),
        migrations.AddConstraint(
            model_name='promotioncodeusagemodel',
            constraint=models.UniqueConstraint(fields=('promotion_code', 'order'), name='unique_promotion_code_order'),
        ),
        migrations.AddIndex(
            model_name='sellitembundleitemmodel',
            index=models.Index(fields=['bundle_sell_item'], name='kkt_rfc_ord_bundle__df3ad8_idx'),
        ),
        migrations.AddIndex(
            model_name='sellitembundleitemmodel',
            index=models.Index(fields=['component_sell_item'], name='kkt_rfc_ord_compone_8125a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='sellitembundleitemmodel',
            constraint=models.UniqueConstraint(fields=('bundle_sell_item', 'component_sell_item'), name='unique_bundle_component'),
        ),
        migrations.AddConstraint(
            model_name='sellitembundleitemmodel',
            constraint=models.CheckConstraint(condition=models.Q(('bundle_sell_item_id__isnull', False), models.Q(('bundle_sell_item_id', models.F('component_sell_item_id')), _negated=True)), name='bundle_not_equal_component'),
        ),
        migrations.AddIndex(
            model_name='ordermodel',
            index=models.Index(fields=['paid_at'], name='kkt_rfc_ord_paid_at_b61fbf_idx'),
        ),
        migrations.AddIndex(
            model_name='ordermodel',
            index=models.Index(fields=['sell_item', 'paid_at'], name='kkt_rfc_ord_sell_it_2edd1e_idx'),
        ),
        migrations.AddIndex(
            model_name='ordermodel',
            index=models.Index(fields=['payment_transaction_id'], name='kkt_rfc_ord_payment_ec553b_idx'),
        ),
        migrations.AddConstraint(
            model_name='ordermodel',
            constraint=models.CheckConstraint(condition=models.Q(('visitor__isnull', False), ('buyer_email__isnull', False), _connector='OR'), name='order_requires_visitor_or_email'),
        ),
        migrations.AddIndex(
            model_name='orderitemmodel',
            index=models.Index(fields=['order'], name='kkt_rfc_ord_order_i_458d81_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitemmodel',
            index=models.Index(fields=['sell_item'], name='kkt_rfc_ord_sell_it_e0c0d4_idx'),
        ),
        migrations.AddIndex(
            model_name='entitlementmodel',
            index=models.Index(fields=['visitor', 'status'], name='kkt_rfc_ord_visitor_da76d9_idx'),
        ),
        migrations.AddIndex(
            model_name='entitlementmodel',
            index=models.Index(fields=['visitor', 'sell_item'], name='kkt_rfc_ord_visitor_9bdedb_idx'),
        ),
        migrations.AddIndex(
            model_name='entitlementmodel',
            index=models.Index(fields=['challenge'], name='kkt_rfc_ord_challen_e26896_idx'),
        ),
        migrations.AddConstraint(
            model_name='entitlementmodel',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('challenge__isnull', True), ('order__isnull', False)), models.Q(('challenge__isnull', False), ('order__isnull', True)), _connector='OR'), name='entitlement_source_mutually_exclusive'),
        ),
        migrations.AddConstraint(
            model_name='entitlementmodel',
            constraint=models.CheckConstraint(condition=models.Q(('order_item__isnull', True), ('order__isnull', False), _connector='OR'), name='order_item_requires_order'),
        ),
        migrations.AddIndex(
            model_name='sellitemtypemodel',
            index=models.Index(fields=['code'], name='kkt_rfc_ord_code_f2008d_idx'),
        ),
        migrations.AddIndex(
            model_name='sellitemmodel',
            index=models.Index(fields=['code'], name='kkt_rfc_ord_code_3bdf87_idx'),
        ),
        migrations.AddIndex(
            model_name='sellitemmodel',
            index=models.Index(fields=['is_bundle'], name='kkt_rfc_ord_is_bund_6369d7_idx'),
        ),
        migrations.AddIndex(
            model_name='sellitemmodel',
            index=models.Index(fields=['sell_item_type'], name='kkt_rfc_ord_sell_it_a5ab39_idx'),
        ),
        migrations.AddIndex(
            model_name='vouchermodel',
            index=models.Index(fields=['voucher_type'], name='kkt_rfc_ord_voucher_d832fb_idx'),
        ),
        migrations.AddIndex(
            model_name='vouchermodel',
            index=models.Index(fields=['order'], name='kkt_rfc_ord_order_i_7b4f3e_idx'),
        ),
        migrations.AddIndex(
            model_name='vouchermodel',
            index=models.Index(fields=['order_item'], name='kkt_rfc_ord_order_i_534548_idx'),
        ),
        migrations.AddIndex(
            model_name='vouchermodel',
            index=models.Index(fields=['sell_item'], name='kkt_rfc_ord_sell_it_f0c509_idx'),
        ),
        migrations.AddIndex(
            model_name='vouchermodel',
            index=models.Index(fields=['entitlement'], name='kkt_rfc_ord_entitle_3dee42_idx'),
        ),
    ]
