# Generated by Django 5.1.1 on 2026-02-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkt_rfc_order', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellitemmodel',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='售价（与 order 表保持一致）', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sellitemmodel',
            name='currency',
            field=models.CharField(default='CNY', help_text='币种（与 order 表保持一致）', max_length=8),
        ),
    ]
