# Generated by Django 5.1.1 on 2026-02-07 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkt_rfc_challenge', '0002_initial'),
        ('kkt_rfc_login', '0003_remove_activationcodemodel_bound_at_and_more'),
        ('kkt_rfc_order', '0004_init_sell_item_type_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='entitlementmodel',
            name='entitlement_source_mutually_exclusive',
        ),
        migrations.AddField(
            model_name='entitlementmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='管理员手动创建时的操作人（不为空 = 管理员操作，order/order_item 可为空）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_created_entitlements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entitlementmodel',
            name='order',
            field=models.ForeignKey(blank=True, help_text='来源订单（奖励/管理员手动创建 可为空）', null=True, on_delete=django.db.models.deletion.CASCADE, to='kkt_rfc_order.ordermodel'),
        ),
        migrations.AlterField(
            model_name='entitlementmodel',
            name='order_item',
            field=models.ForeignKey(blank=True, help_text='用于套餐/多行订单的精确追溯与对账；奖励/补发/管理员手动创建 可为空', null=True, on_delete=django.db.models.deletion.CASCADE, to='kkt_rfc_order.orderitemmodel'),
        ),
        migrations.AddIndex(
            model_name='entitlementmodel',
            index=models.Index(fields=['created_by'], name='kkt_rfc_ord_created_9229f4_idx'),
        ),
        migrations.AddConstraint(
            model_name='entitlementmodel',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('challenge__isnull', True), ('created_by__isnull', True), ('order__isnull', False)), models.Q(('challenge__isnull', False), ('created_by__isnull', True), ('order__isnull', True)), models.Q(('challenge__isnull', True), ('created_by__isnull', False), ('order__isnull', True)), _connector='OR'), name='entitlement_source_mutually_exclusive'),
        ),
    ]
