# Generated by Django 5.1.1 on 2026-02-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkt_rfc_order', '0005_remove_entitlementmodel_entitlement_source_mutually_exclusive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellitemmodel',
            name='category',
            field=models.CharField(choices=[('PACKAGE', 'Package'), ('ADD_ON', 'Add-on')], db_index=True, default='ADD_ON', help_text='售卖项类别（PACKAGE=套餐包，任何人可购买；ADD_ON=附加项，需登录态）', max_length=20),
        ),
        migrations.AlterField(
            model_name='sellitemmodel',
            name='purchasable_identity',
            field=models.CharField(choices=[('ANY', 'Any'), ('ACTIVATION_CODE_ONLY', 'Activation Code Only'), ('NFC_ONLY', 'NFC Only'), ('LOGGED_IN', 'Logged In'), ('BOTH', 'Both')], default='LOGGED_IN', help_text='可购买人群（ANY=任何人含email-only；LOGGED_IN=需登录态；BOTH=兼容旧值等同LOGGED_IN）', max_length=20),
        ),
    ]
