# Generated by Django 5.1.1 on 2026-02-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkt_rfc_order', '0006_add_category_to_sell_item'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ordermodel',
            name='order_requires_visitor_or_email',
        ),
        migrations.RenameField(
            model_name='ordermodel',
            old_name='buyer_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='ordermodel',
            old_name='sales_poi',
            new_name='poi',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='原价金额（优惠前）', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sellitemmodel',
            name='purchasable_identity',
            field=models.CharField(choices=[('ANY', 'Any'), ('ACTIVATION_CODE_ONLY', 'Activation Code Only'), ('NFC_ONLY', 'NFC Only'), ('LOGGED_IN', 'Logged In')], default='LOGGED_IN', help_text='可购买人群（ANY=任何人含email-only；LOGGED_IN=需登录态；ACTIVATION_CODE_ONLY=仅激活码用户；NFC_ONLY=仅NFC用户）', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='ordermodel',
            constraint=models.CheckConstraint(condition=models.Q(('visitor__isnull', False), ('email__isnull', False), _connector='OR'), name='order_requires_visitor_or_email'),
        ),
    ]
