# Generated by Django 5.1.1 on 2026-02-10 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkt_rfc_login', '0006_add_nfc_requires_activation_code_constraint'),
        ('kkt_rfc_order', '0008_merge_sell_item_type_into_sell_item'),
        ('kkt_rfc_tour_guide', '0025_feedbackmodel_page_url_feedbackmodel_task_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='poi',
            field=models.ForeignKey(blank=True, help_text='销售发生的POI（线下点位下单可填；线上可空）', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kkt_rfc_tour_guide.poimodel'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='visitor',
            field=models.ForeignKey(blank=True, help_text='关联购买者，仅当 order.sell_item.sell_item_type_code = ACTIVATION_CODE 时允许为空；其余订单必须有关联的 visitor', null=True, on_delete=django.db.models.deletion.CASCADE, to='kkt_rfc_login.visitormodel'),
        ),
    ]
