# Generated by Django 5.1.1 on 2026-02-10 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkt_rfc_login', '0006_add_nfc_requires_activation_code_constraint'),
        ('kkt_rfc_order', '0009_alter_ordermodel_poi_alter_ordermodel_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='visitor',
            field=models.ForeignKey(blank=True, help_text='关联购买者（email-only 购买 Package 时也会创建 visitor）', null=True, on_delete=django.db.models.deletion.CASCADE, to='kkt_rfc_login.visitormodel'),
        ),
        migrations.AlterField(
            model_name='sellitemmodel',
            name='activation_mode',
            field=models.CharField(choices=[('REDEEM_REQUIRED', 'Redeem Required'), ('IMMEDIATE', 'Immediate')], default='REDEEM_REQUIRED', help_text='激活/履约方式（REDEEM_REQUIRED=需核销；IMMEDIATE=购买/激活即生效，不生成voucher）', max_length=20),
        ),
        migrations.AlterField(
            model_name='sellitemmodel',
            name='sell_item_type_code',
            field=models.CharField(blank=True, choices=[('MEMORY', 'Memory'), ('TICKET', 'Ticket'), ('FOOD', 'Food'), ('CHALLENGE_PRIZE', 'Challenge Prize')], db_index=True, help_text='售卖项类型编码（MEMORY/TICKET/FOOD/CHALLENGE_PRIZE）', max_length=64, null=True),
        ),
    ]
