# Generated by Django 5.1.1 on 2026-02-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkt_rfc_order', '0010_remove_activation_code_type_and_none_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellitemmodel',
            name='sell_item_type_code',
            field=models.CharField(blank=True, choices=[('MEMORY', 'Memory'), ('TICKET', 'Ticket'), ('FOOD_TOUR', 'Food Tour'), ('CHALLENGE_PRIZE', 'Challenge Prize')], db_index=True, help_text='售卖项类型编码（MEMORY/TICKET/FOOD_TOUR/CHALLENGE_PRIZE）', max_length=64, null=True),
        ),
    ]
