# Generated by Django 5.1.1 on 2026-03-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kkt_rfc_order', '0012_order_sell_item_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellitemmodel',
            name='sell_item_type_code',
            field=models.CharField(blank=True, choices=[('MEMORY', 'Memory'), ('TICKET', 'Ticket'), ('FOOD_TOUR', 'Food Tour'), ('CHALLENGE_PRIZE', 'Challenge Prize'), ('ACTIVATION_CODE', 'Activation Code'), ('CANVAS', 'Canvas')], db_index=True, help_text='售卖项类型编码（MEMORY/TICKET/FOOD_TOUR/CHALLENGE_PRIZE/ACTIVATION_CODE/CANVAS）', max_length=64, null=True),
        ),
    ]
